// Code generated by "stringer -type=Tile"; DO NOT EDIT.

package score

import "strconv"

const (
	_Tile_name_0 = "NoTile"
	_Tile_name_1 = "ballsBaseBalls1Balls2Balls3Balls4Balls5Balls6Balls7Balls8Balls9charsBaseChars1Chars2Chars3Chars4Chars5Chars6Chars7Chars8Chars9bambooBaseBamboo1Bamboo2Bamboo3Bamboo4Bamboo5Bamboo6Bamboo7Bamboo8Bamboo9windBaseWindEastWindSouthWindWestWindNorth"
	_Tile_name_2 = "dragonBaseDragonRedDragonGreenDragonWhite"
	_Tile_name_3 = "flowerBaseFlower1Flower2Flower3Flower4"
	_Tile_name_4 = "seasonBaseSeason1Season2Season3Season4"
)

var (
	_Tile_index_1 = [...]uint8{0, 9, 15, 21, 27, 33, 39, 45, 51, 57, 63, 72, 78, 84, 90, 96, 102, 108, 114, 120, 126, 136, 143, 150, 157, 164, 171, 178, 185, 192, 199, 207, 215, 224, 232, 241}
	_Tile_index_2 = [...]uint8{0, 10, 19, 30, 41}
	_Tile_index_3 = [...]uint8{0, 10, 17, 24, 31, 38}
	_Tile_index_4 = [...]uint8{0, 10, 17, 24, 31, 38}
)

func (i Tile) String() string {
	switch {
	case i == 0:
		return _Tile_name_0
	case 10 <= i && i <= 44:
		i -= 10
		return _Tile_name_1[_Tile_index_1[i]:_Tile_index_1[i+1]]
	case 50 <= i && i <= 53:
		i -= 50
		return _Tile_name_2[_Tile_index_2[i]:_Tile_index_2[i+1]]
	case 60 <= i && i <= 64:
		i -= 60
		return _Tile_name_3[_Tile_index_3[i]:_Tile_index_3[i+1]]
	case 70 <= i && i <= 74:
		i -= 70
		return _Tile_name_4[_Tile_index_4[i]:_Tile_index_4[i+1]]
	default:
		return "Tile(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
